# -*- coding: utf-8 -*-
import os

path = r'c:\Users\ASUS\Documents\Website\kader-panel-pmii-justicia\public\pages\dashboard.html'

html = '<!DOCTYPE html>\n<html lang="id">\n<head>\n<meta charset="UTF-8">\n<meta name="viewport" content="width=device-width, initial-scale=1.0">\n<title>Dashboard - Kader Panel PMII Justicia</title>\n<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.0/css/all.min.css">\n<style>\n'
css = ':root{--sidebar-w:260px;--header-h:64px;--primary:#1a237e;--bg:#f0f2f5;--bg-card:#fff;--text:#212121;--text2:#616161;--border:#e0e0e0;--shadow:0 2px 8px rgba(0,0,0,.08);--radius:12px;--radius-sm:8px;--transition:.3s}\n[data-theme="dark"]{--bg:#0f1219;--bg-card:#1a1f2e;--text:#e8eaed;--text2:#9aa0a6;--border:#2d3348}\n*{margin:0;padding:0;box-sizing:border-box}\n'
css += 'body{font-family:Segoe UI,sans-serif;background:var(--bg);color:var(--text);overflow-x:hidden;min-height:100vh;transition:.3s}\n'
css += '.dash-layout{display:flex;min-height:100vh}\n'
css += '.sidebar{position:fixed;left:0;top:0;bottom:0;width:260px;background:linear-gradient(180deg,#1a237e,#0d1466);color:#fff;z-index:1000;overflow-y:auto;transition:.3s;display:flex;flex-direction:column}\n'
css += '.sidebar-brand{padding:18px 20px;border-bottom:1px solid rgba(255,255,255,.1);display:flex;align-items:center;gap:12px}\n'
css += '.sidebar-brand .brand-icon{width:40px;height:40px;background:rgba(255,255,255,.15);border-radius:10px;display:flex;align-items:center;justify-content:center;font-size:1.4rem}\n'
css += '.sidebar-brand h2{font-size:1rem;font-weight:700}\n.sidebar-brand small{font-size:.7rem;opacity:.7;display:block}\n'
css += '.sidebar-nav{padding:12px 0;flex:1}\n.sidebar-label{padding:8px 20px 4px;font-size:.65rem;text-transform:uppercase;opacity:.5;font-weight:600}\n'
css += '.sidebar-link{display:flex;align-items:center;gap:12px;padding:10px 20px;color:rgba(255,255,255,.7);text-decoration:none;font-size:.85rem;transition:.3s;border-left:3px solid transparent;cursor:pointer}\n'
css += '.sidebar-link:hover{background:rgba(255,255,255,.08);color:#fff}\n'
css += '.sidebar-link.active{background:rgba(255,255,255,.12);color:#fff;border-left-color:#ffd600}\n'
css += '.sidebar-link i{width:20px;text-align:center}\n'
css += '.sidebar-footer{padding:16px 20px;border-top:1px solid rgba(255,255,255,.1);font-size:.75rem;opacity:.5;text-align:center}\n'
css += '.main-area{margin-left:260px;flex:1;min-height:100vh;display:flex;flex-direction:column}\n'
css += '.topbar{background:var(--bg-card);height:64px;display:flex;align-items:center;padding:0 24px;gap:16px;border-bottom:1px solid var(--border);position:sticky;top:0;z-index:100}\n'
css += '.topbar-left{display:flex;align-items:center;gap:12px}\n.hamburger{display:none;background:none;border:none;color:var(--text);font-size:1.3rem;cursor:pointer;padding:4px}\n'
css += '.topbar-right{display:flex;align-items:center;gap:12px;margin-left:auto}\n'
css += '.theme-btn{background:var(--bg);border:1px solid var(--border);border-radius:8px;width:36px;height:36px;display:flex;align-items:center;justify-content:center;cursor:pointer;color:var(--text2)}\n'
css += '.topbar-clock{font-size:.8rem;color:var(--text2);text-align:right}\n.topbar-clock .clock-time{font-weight:700;font-size:.95rem;color:var(--text)}\n'
css += '.topbar-user{display:flex;align-items:center;gap:10px;padding:4px 8px;border-radius:8px;cursor:pointer}\n'
css += '.topbar-user .u-avatar{width:34px;height:34px;border-radius:50%;background:var(--primary);color:#fff;display:flex;align-items:center;justify-content:center;font-weight:700;font-size:.8rem}\n'
css += '.topbar-user .u-name{font-size:.85rem;font-weight:600}\n.topbar-user .u-role{font-size:.7rem;color:var(--text2)}\n'
css += '.dash-content{padding:24px;flex:1}\n.page-title{font-size:1.5rem;font-weight:700;margin-bottom:4px}\n'
css += '.page-subtitle{font-size:.85rem;color:var(--text2);margin-bottom:24px}\n'
css += '.stats-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(200px,1fr));gap:16px;margin-bottom:24px}\n'
css += '.stat-card{background:var(--bg-card);border-radius:12px;padding:20px;border:1px solid var(--border);transition:.3s}\n'
css += '.stat-card:hover{transform:translateY(-2px);box-shadow:var(--shadow)}\n'
css += '.sib{width:44px;height:44px;border-radius:10px;display:flex;align-items:center;justify-content:center;font-size:1.2rem;margin-bottom:14px}\n'
css += '.sl{font-size:.8rem;color:var(--text2);margin-bottom:4px}\n.sv{font-size:1.8rem;font-weight:800}\n'
css += '.sib.purple{background:#e8eaf6;color:#1a237e}.sib.green{background:#e8f5e9;color:#2e7d32}.sib.orange{background:#fff3e0;color:#e65100}\n'
css += '.sib.blue{background:#e3f2fd;color:#1565c0}.sib.red{background:#fce4ec;color:#c62828}.sib.teal{background:#e0f2f1;color:#00695c}\n'
css += '[data-theme="dark"] .sib.purple{background:rgba(26,35,126,.3)}[data-theme="dark"] .sib.green{background:rgba(46,125,50,.3)}\n'
css += '[data-theme="dark"] .sib.orange{background:rgba(230,81,0,.3)}[data-theme="dark"] .sib.blue{background:rgba(21,101,192,.3)}\n'
css += '[data-theme="dark"] .sib.red{background:rgba(198,40,40,.3)}[data-theme="dark"] .sib.teal{background:rgba(0,105,92,.3)}\n'
css += '.dash-grid{display:grid;grid-template-columns:2fr 1fr;gap:20px;margin-bottom:24px}\n'
css += '@media(max-width:900px){.dash-grid{grid-template-columns:1fr}}\n'
css += '.card{background:var(--bg-card);border-radius:12px;border:1px solid var(--border);overflow:hidden}\n'
css += '.card-hd{padding:16px 20px;border-bottom:1px solid var(--border);display:flex;align-items:center;justify-content:space-between}\n'
css += '.card-hd h3{font-size:.95rem;font-weight:700}\n.card-hd .ca{font-size:.8rem;color:var(--primary);cursor:pointer;text-decoration:none}\n'
css += '.card-bd{padding:16px 20px}\n'
css += '.ai{padding:12px 0;border-bottom:1px solid var(--border);display:flex;gap:12px}\n.ai:last-child{border-bottom:none}\n'
css += '.ai-icon{width:36px;height:36px;border-radius:8px;background:var(--bg);display:flex;align-items:center;justify-content:center;font-size:.9rem;color:var(--primary)}\n'
css += '.ai-info{flex:1;min-width:0}\n.ai-title{font-size:.85rem;font-weight:600;margin-bottom:2px}\n.ai-meta{font-size:.75rem;color:var(--text2);display:flex;gap:8px}\n'
css += '.ei{padding:10px 0;border-bottom:1px solid var(--border);display:flex;gap:12px;align-items:flex-start}\n.ei:last-child{border-bottom:none}\n'
css += '.ed{width:40px;text-align:center;flex-shrink:0}\n.ed .ed-d{font-size:1.1rem;font-weight:800;display:block}\n.ed .ed-m{font-size:.65rem;text-transform:uppercase;color:var(--text2);display:block}\n'
css += '.ei .einfo{flex:1;min-width:0}\n.ei .einfo .et{font-size:.85rem;font-weight:600;margin-bottom:2px}\n.ei .einfo .em{font-size:.75rem;color:var(--text2);display:flex;gap:8px;flex-wrap:wrap}\n'
css += '.e-dot{width:8px;height:8px;border-radius:50%;flex-shrink:0;margin-top:4px}\n'
css += '.uic{display:flex;flex-direction:column;align-items:center;padding:24px 20px;text-align:center}\n'
css += '.uia{width:72px;height:72px;border-radius:50%;background:var(--primary);color:#fff;display:flex;align-items:center;justify-content:center;font-size:1.8rem;font-weight:700;margin-bottom:12px}\n'
css += '.uin{font-size:1.1rem;font-weight:700;margin-bottom:2px}\n.uir{font-size:.85rem;color:var(--primary);font-weight:600;margin-bottom:4px}\n'
css += '.uie{font-size:.8rem;color:var(--text2);margin-bottom:12px}\n'
css += '.uis{display:flex;gap:20px;width:100%;justify-content:center;border-top:1px solid var(--border);padding-top:12px;margin-top:8px}\n'
css += '.uis-item{text-align:center}\n.uis-item .uis-v{font-size:1.1rem;font-weight:700;display:block}\n.uis-item .uis-l{font-size:.7rem;color:var(--text2);text-transform:uppercase}\n'
css += '.ls{display:flex;justify-content:center;align-items:center;min-height:160px;color:var(--text2);gap:10px}\n'
css += '.ls i{font-size:2rem;animation:spin 1s linear infinite}\n@keyframes spin{100%{transform:rotate(360deg)}}\n'
css += '.emp{padding:40px 20px;text-align:center;color:var(--text2)}\n.emp i{font-size:2.5rem;margin-bottom:8px;display:block;opacity:.5}\n'
css += '@media(max-width:768px){.sidebar{transform:translateX(-100%)}.sidebar.open{transform:translateX(0)}.main-area{margin-left:0}.hamburger{display:block}.topbar-clock{display:none}.dash-content{padding:16px}.stats-grid{grid-template-columns:repeat(2,1fr)}}\n'

html += css + '\n</style>\n</head>\n<body>\n<div class="dash-layout">\n<aside class="sidebar" id="sidebar">\n<div class="sidebar-brand">\n<div class="brand-icon"><i class="fas fa-people-arrows"></i></div>\n<div><h2>Kader Panel</h2><small>PMII Justicia UNESA</small></div>\n</div>\n<nav class="sidebar-nav">\n<div class="sidebar-label">Menu</div>\n<a class="sidebar-link active" href="dashboard.html"><i class="fas fa-th-large"></i> Dashboard</a>\n<a class="sidebar-link" href="users.html"><i class="fas fa-users"></i> Pengguna</a>\n<a class="sidebar-link" href="organization.html"><i class="fas fa-sitemap"></i> Struktur</a>\n<a class="sidebar-link" href="calendar.html"><i class="fas fa-calendar"></i> Event</a>\n<a class="sidebar-link" href="announcements.html"><i class="fas fa-bullhorn"></i> Pengumuman</a>\n<div class="sidebar-label">Akun</div>\n<a class="sidebar-link" id="logoutBtn"><i class="fas fa-sign-out-alt"></i> Keluar</a>\n</nav>\n<div class="sidebar-footer">PMII Rayon Justicia &copy; 2025</div>\n</aside>\n<div class="main-area">\n<header class="topbar">\n<div class="topbar-left">\n<button class="hamburger" id="hamburger"><i class="fas fa-bars"></i></button>\n<strong style="color:var(--primary)"><i class="fas fa-tachometer-alt"></i> Dashboard</strong>\n</div>\n<div class="topbar-right">\n<div class="topbar-clock"><div class="clock-time" id="clockTime">--:--:--</div><div id="clockDate">---, -- --- ----</div>\n<button class="theme-btn" id="themeToggle"><i class="fas fa-moon"></i></button>\n<div class="topbar-user"><div class="u-avatar" id="userAvatar">K</div><div class="u-info"><div class="u-name" id="userName">Kader</div><div class="u-role" id="userRole">-</div></div>\n</div>\n</header>\n<main class="dash-content">\n<h1 class="page-title">Dashboard</h1>\n<p class="page-subtitle">Selamat datang kembali, <strong id="welcomeUser">Kader</strong>!</p>\n<div class="stats-grid" id="statsGrid">\n<div class="stat-card"><div class="sib purple"><i class="fas fa-users"></i></div><div class="sl">Total Anggota</div><div class="sv" id="statTotal">-</div>\n<div class="stat-card"><div class="sib green"><i class="fas fa-user-check"></i></div><div class="sl">Anggota Aktif</div><div class="sv" id="statActive">-</div>\n<div class="stat-card"><div class="sib orange"><i class="fas fa-calendar-check"></i></div><div class="sl">Event Hari Ini</div><div class="sv" id="statToday">0</div>\n<div class="stat-card"><div class="sib blue"><i class="fas fa-calendar-week"></i></div><div class="sl">Event Minggu Ini</div><div class="sv" id="statWeek">0</div>\n<div class="stat-card"><div class="sib teal"><i class="fas fa-layer-group"></i></div><div class="sl">Total Bidang</div><div class="sv" id="statDiv">-</div>\n<div class="stat-card"><div class="sib red"><i class="fas fa-bullhorn"></i></div><div class="sl">Pengumuman</div><div class="sv" id="statAnn">-</div>\n</div>\n<div class="dash-grid">\n<div class="card">\n<div class="card-hd"><h3><i class="fas fa-bullhorn"></i> Pengumuman Terbaru</h3><a href="announcements.html" class="ca">Lihat Semua &rarr;</a></div>\n<div class="card-bd" id="annList"><div class="ls"><i class="fas fa-spinner"></i> Memuat...</div>\n</div>\n<div>\n<div class="card" style="margin-bottom:20px">\n<div class="card-hd"><h3><i class="fas fa-user-circle"></i> Profil Saya</h3></div>\n<div class="card-bd" id="profileCard"><div class="ls"><i class="fas fa-spinner"></i> Memuat...</div>\n</div>\n<div class="card">\n<div class="card-hd"><h3><i class="fas fa-calendar-alt"></i> Event Mendatang</h3><a href="calendar.html" class="ca">Lihat</a></div>\n<div class="card-bd" id="evtList"><div class="ls"><i class="fas fa-spinner"></i> Memuat...</div>\n</div>\n</div>\n</div>\n</main>\n</div>\n</div>\n<script>\n'
js = 'function $(i){return document.getElementById(i)}\n'
js += 'function init(n){if(!n)return'?';return n.split(' ').map(function(w){return w[0]}).join('').substr(0,2).toUpperCase()}\n'
js += 'function gm(d){var m=['Jan','Feb','Mar','Apr','Mei','Jun','Jul','Ags','Sep','Okt','Nov','Des'];return m[d.getMonth()]}\n'
js += 'function gd(d){var h=['Minggu','Senin','Selasa','Rabu','Kamis','Jumat','Sabtu'];return h[d.getDay()]}\n'
js += 'function fd(d){var n=new Date(d);return gd(n)+', '+n.getDate()+' '+gm(n)+' '+n.getFullYear()}\n'
js += 'var tt=$(themeToggle),ti=tt.querySelector(i);\n'
js += 'if(localStorage.getItem(theme)===dark||(!localStorage.getItem(theme)&&window.matchMedia((prefers-color-scheme:dark)).matches)){document.documentElement.setAttribute(data-theme,dark);ti.className=fas fa-sun;}\n'
js += 'tt.onclick=function(){var t=document.documentElement.getAttribute(data-theme);if(t===dark){document.documentElement.removeAttribute(data-theme);localStorage.setItem(theme,light);ti.className=fas fa-moon;}else{document.documentElement.setAttribute(data-theme,dark);localStorage.setItem(theme,dark);ti.className=fas fa-sun;}};\n'
js += 'function updClock(){var d=new Date().toLocaleString(id-ID,{timeZone:Asia/Jakarta});var n=new Date(d);var h=String(n.getHours()).padStart(2,0<execute_command>
<command>dir "c:\Users\ASUS\Documents\Website\Rayon PMII Justicia UNESA\fix_dashboard_final.py"</command>
</execute_filtered_text>
